CREATE TABLE Dimension_Temps(
ID_DIM_TEMP VARCHAR(250),
ANNEE VARCHAR(250),
MOIS VARCHAR(250),
SEMAINE VARCHAR(250),
JOUR VARCHAR(250),
PRIMARY KEY(ID_DIM_TEMP)
);



CREATE TABLE Dimension_produit(
ID_DIM_PRODUIT VARCHAR(250),
NOM VARCHAR(250),
CATEGORIE VARCHAR(250),
SOUS_CATEGORIE VARCHAR(250),
PRIMARY KEY(ID_DIM_PRODUIT)
);



CREATE TABLE Dimension_Client(
ID_DIM_CLIENT VARCHAR(250),
NOM VARCHAR(250),
ADRESSE VARCHAR(250),
CITY VARCHAR(80),
POSTAL_CODE VARCHAR(250),
PAYS VARCHAR(100),
PRIMARY KEY(ID_DIM_CLIENT)
);



CREATE TABLE Dimension_Fournisseur(
ID_DIM_FOURNISSEUR VARCHAR(250),
NOM VARCHAR(250),
Addresse VARCHAR(250),
VILLE VARCHAR(80),
PAYS VARCHAR(100),
ACCOUNT_NUMMBER VARCHAR(250),
PRIMARY KEY(ID_DIM_FOURNISSEUR)
);



CREATE TABLE Dimension_Géographique__de_la_vente_(
ID_DIM_GEO VARCHAR(250),
Territory_NAME VARCHAR(250),
Region_Code VARCHAR(250),
_Group VARCHAR(250),
PRIMARY KEY(ID_DIM_GEO)
);



CREATE TABLE Table_des_Faits__Vente(
ID_FAIT_ANALYSE VARCHAR(50),
ID_DIM_DATE_COMMANDE VARCHAR(50),
PRIX_de_VENTE VARCHAR(50),
QUANTITE VARCHAR(50),
PRIX_FOURNISSEUR CURRENCY,
ID_DIM_FOURNISSEUR VARCHAR(250) NOT NULL,
ID_DIM_TEMP VARCHAR(250) NOT NULL,
ID_DIM_GEO VARCHAR(250) NOT NULL,
ID_DIM_PRODUIT VARCHAR(250) NOT NULL,
ID_DIM_CLIENT VARCHAR(250) NOT NULL,
PRIMARY KEY(ID_FAIT_ANALYSE),
FOREIGN KEY(ID_DIM_FOURNISSEUR) REFERENCES Dimension_Fournisseur(ID_DIM_FOURNISSEUR),
FOREIGN KEY(ID_DIM_TEMP) REFERENCES Dimension_Temps(ID_DIM_TEMP),
FOREIGN KEY(ID_DIM_GEO) REFERENCES Dimension_Géographique__de_la_vente_(ID_DIM_GEO),
FOREIGN KEY(ID_DIM_PRODUIT) REFERENCES Dimension_produit(ID_DIM_PRODUIT),
FOREIGN KEY(ID_DIM_CLIENT) REFERENCES Dimension_Client(ID_DIM_CLIENT)
);